export const ENG_IPA_INPUT_CHANGED = 'ENG_IPA_INPUT_CHANGED';
export const ENG_IPA_CHECK_SCORE = 'ENG_IPA_CHECK_SCORE';

export const IPA_ENG_INPUT_CHANGED = 'IPA_ENG_INPUT_CHANGED';
export const IPA_ENG_CHECK_SCORE = 'IPA_ENG_CHECK_SCORE';